USE [master]
GO

/****** Object:  Database [UniDB]    Script Date: 6/2/2023 10:23:46 PM ******/
CREATE DATABASE [UniDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UniDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UniDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UniDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UniDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UniDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UniDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UniDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UniDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UniDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UniDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [UniDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UniDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UniDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UniDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UniDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UniDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UniDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UniDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UniDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UniDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [UniDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UniDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UniDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UniDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UniDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UniDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UniDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UniDB] SET RECOVERY FULL 
GO

ALTER DATABASE [UniDB] SET  MULTI_USER 
GO

ALTER DATABASE [UniDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UniDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UniDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UniDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UniDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UniDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UniDB] SET  READ_WRITE 
GO

